name: Familienrecht
favicon: null
layout_spectrum: 0.23102991981431842
typography_spectrum: 0.5815059437882155
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7626090480480343
  lightness: 0.22063867468386889
  saturation: 0.72672950476408
  rhythmicContrast: 0.326319036539644
purpose: []
